import os
import re

import discord
from discord import app_commands
from discord.ext import commands


class ServerConstants(commands.Cog):
    """🐾 Wooper Server Constants Extractor Cog 🐾"""

    def __init__(self, bot: commands.Bot):
        self.bot = bot
        # Optional server aliases for shorter class names
        self.SERVER_ALIASES = {
            "Meow Clan Summit": "MCS",
        }

    def sanitize_name(self, name: str) -> str:
        """✨ Keep underscores, convert dashes to underscores, remove emojis/special chars ✨"""
        name = name.replace("-", "_")  # staff-chat -> staff_chat
        name = re.sub(r"[^\w\s_]", "", name)  # remove other symbols & emojis
        name = re.sub(r"\s+", "_", name)  # spaces -> underscores
        return name.lower()

    def sanitize_filename(self, name: str) -> str:
        """💌 Sanitize server name for filename"""
        name = re.sub(r"[^\w\s]", "", name)
        name = re.sub(r"\s+", "_", name)
        return name.lower() + "_constants.py"

    # -------------------- Safe variable names helper --------------------
    def safe_name(self, name: str) -> str:
        """✨ Make a name safe for Python variables (prefix number with _) ✨"""
        name = self.sanitize_name(name)  # call sanitize_name, not itself!
        if re.match(r"^\d", name):  # starts with a number
            name = f"_{name}"
        if not name:  # empty names
            name = "_unknown"
        return name

    #
    def update_constants_file(
        self,
        filename: str,
        class_suffix: str,
        items: dict,
        guild_name: str,
        group_by_category: bool = False,
    ):
        """🟦 Create or update a constants class in the file, skip if empty"""
        if not items:
            return  # skip empty sections

        # -------------------- Use alias if available --------------------
        alias = getattr(self, "SERVER_ALIASES", {}).get(
            guild_name, self.safe_name(guild_name).upper()
        )
        class_name = f"{alias}_{class_suffix}"

        # -------------------- Create file if missing --------------------
        if not os.path.exists(filename):
            with open(filename, "w", encoding="utf-8") as f:
                f.write(f"# 🐾 Generated by Wooper for server constants 🐾\n\n")

        # -------------------- Read existing content --------------------
        with open(filename, "r", encoding="utf-8") as f:
            content = f.read()

        # -------------------- Prepare new class content --------------------
        class_lines = [
            f"# 💦☁────────────────────────────────────────────💦☁\n",
            f"#       {class_name}\n",
            f"# 💦☁────────────────────────────────────────────💦☁\n",
            f"class {class_name}:\n\n",
        ]

        if group_by_category:
            # items should be: {category_name: {channel_name: id}}
            for cat_name, cat_channels in items.items():
                class_lines.append(
                    f"    \n# 🌊💙🤍───────────── {cat_name} ─────────────💙🤍🌊\n\n"
                )
                for ch_name, ch_id in cat_channels.items():
                    class_lines.append(f"    {ch_name} = {ch_id}\n")
        else:
            for name, id in items.items():
                # Wrap in quotes if it's an emoji string starting with '<'
                if isinstance(id, str) and id.startswith("<"):
                    class_lines.append(f'    {name} = "{id}"\n')
                else:
                    class_lines.append(f"    {name} = {id}\n")

        new_class_content = "".join(class_lines)

        # -------------------- Merge if class exists --------------------
        if f"class {class_name}:" in content:
            pattern = re.compile(rf"class {class_name}:\n(.*?)(\n\n|$)", re.DOTALL)
            match = pattern.search(content + "\n\n")
            existing_lines = {}
            if match:
                for line in match.group(1).splitlines():
                    if "=" in line:
                        k, v = line.strip().split(" = ", 1)
                        # Remove surrounding quotes if present
                        if v.startswith('"') and v.endswith('"'):
                            v = v[1:-1]
                        existing_lines[k] = v

            # Add new items if missing
            for k, v in items.items():
                if k not in existing_lines:
                    existing_lines[k] = v

            merged_lines = [
                f"# 💦☁────────────────────────────────────────────💦☁\n",
                f"#       {class_name}\n",
                f"# 💦☁────────────────────────────────────────────💦☁\n",
                f"class {class_name}:\n",
            ]
            for k, v in existing_lines.items():
                if isinstance(v, str) and v.startswith("<"):
                    merged_lines.append(f'    {k} = "{v}"\n')
                else:
                    merged_lines.append(f"    {k} = {v}\n")

            merged_content = "".join(merged_lines)
            content = pattern.sub(merged_content + "\n\n", content)
        else:
            content += "\n" + new_class_content + "\n"

        # -------------------- Write updated content --------------------
        with open(filename, "w", encoding="utf-8") as f:
            f.write(content)

    @app_commands.command(
        name="list-server", description="🐾 Extract server info and save constants 🐾"
    )
    @app_commands.default_permissions(administrator=True)
    async def list_server(self, interaction: discord.Interaction):
        guild = interaction.guild
        filename = self.sanitize_filename(guild.name)

        # -------------------- Channels grouped by category --------------------
        text_channels_by_cat = {}
        voice_channels_by_cat = {}
        stage_channels_by_cat = {}
        news_channels_by_cat = {}

        for ch in guild.channels:
            name = self.safe_name(ch.name)
            cat_name = (
                ch.category.name if getattr(ch, "category", None) else "Uncategorized"
            )
            cat_name = self.safe_name(cat_name).title()

            if isinstance(ch, discord.TextChannel):
                # Check if it's a news channel
                if getattr(ch, "is_news", lambda: False)():
                    news_channels_by_cat.setdefault(cat_name, {})[name] = ch.id
                else:
                    text_channels_by_cat.setdefault(cat_name, {})[name] = ch.id
            elif isinstance(ch, discord.VoiceChannel):
                voice_channels_by_cat.setdefault(cat_name, {})[name] = ch.id
            elif isinstance(ch, discord.StageChannel):
                stage_channels_by_cat.setdefault(cat_name, {})[name] = ch.id
            elif isinstance(ch, discord.ForumChannel):
                news_channels_by_cat.setdefault(cat_name, {})[name] = ch.id

        self.update_constants_file(
            filename,
            "TEXT_CHANNELS",
            text_channels_by_cat,
            guild.name,
            group_by_category=True,
        )
        self.update_constants_file(
            filename,
            "VOICE_CHANNELS",
            voice_channels_by_cat,
            guild.name,
            group_by_category=True,
        )
        self.update_constants_file(
            filename,
            "STAGE_CHANNELS",
            stage_channels_by_cat,
            guild.name,
            group_by_category=True,
        )
        self.update_constants_file(
            filename,
            "NEWS_CHANNELS",
            news_channels_by_cat,
            guild.name,
            group_by_category=True,
        )
        # -------------------- Categories --------------------
        categories = {}
        for ch in guild.channels:
            if getattr(ch, "category", None):
                cat = ch.category
                cat_name = self.safe_name(cat.name).upper()
                if cat_name not in categories:
                    categories[cat_name] = cat.id

        # Use the same update_constants_file for categories
        self.update_constants_file(filename, "CATEGORIES", categories, guild.name)

        # -------------------- Roles --------------------
        roles = {}
        for r in sorted(guild.roles, key=lambda x: x.position, reverse=True):
            if r.is_default():
                continue
            name = self.safe_name(r.name)
            roles[name] = r.id
        self.update_constants_file(filename, "ROLES", roles, guild.name)

        # -------------------- Emojis (single class) --------------------
        all_emojis = {}
        for e in guild.emojis:
            name = self.safe_name(e.name)
            # Format Discord string
            emoji_str = f"<a:{e.name}:{e.id}>" if e.animated else f"<:{e.name}:{e.id}>"
            all_emojis[name] = emoji_str

        self.update_constants_file(filename, "EMOJIS", all_emojis, guild.name)

        await interaction.response.send_message(
            content=f"✅ Wooper has updated **{filename}** with all your server constants! 💌🐾",
            ephemeral=True,
        )

    list_server.extras = {"category": "Owner"}


# -------------------- Setup Cog --------------------
async def setup(bot: commands.Bot):
    await bot.add_cog(ServerConstants(bot))
