# 🐾 Generated by Wooper for server constants 🐾


# 💦☁────────────────────────────────────────────💦☁
#       STAFFMONS_TEXT_CHANNELS
# 💦☁────────────────────────────────────────────💦☁
class STAFFMONS__TEXT_CHANNELS:

    # 🌊💙🤍───────────── Council ─────────────💙🤍🌊

    hall = 1407467496403107852
    market_snipe = 1407476248917049575
    rare_spawn = 1407541987535491082

    # 🌊💙🤍───────────── Market_Feeds ─────────────💙🤍🌊

    c_u_r_sr_market_feed = 1407470481044541551
    legend_mega_gmax_market_feed = 1407470546861690950
    shiny_market_feed = 1407470595884716172
    golden_market_feed = 1407470752776847390

    # 🌊💙🤍───────────── Quarters ─────────────💙🤍🌊

    sephoria = 1407475984076115999
    fluorescence = 1407476011347742890
    garlic_kebab = 1407525256675201156


# 💦☁────────────────────────────────────────────💦☁
#       STAFFMONS_VOICE_CHANNELS
# 💦☁────────────────────────────────────────────💦☁
class STAFFMONS_VOICE_CHANNELS:


# 🌊💙🤍───────────── Podium ─────────────💙🤍🌊

    general = 1407467496403107853


# 💦☁────────────────────────────────────────────💦☁
#       STAFFMONS_CATEGORIES
# 💦☁────────────────────────────────────────────💦☁
class STAFFMONS_CATEGORIES:

    COUNCIL = 1407467496403107850
    PODIUM = 1407467496403107851
    MARKET_FEEDS = 1407469674878337174
    QUARTERS = 1407478618476511322


# 💦☁────────────────────────────────────────────💦☁
#       STAFFMONS_ROLES
# 💦☁────────────────────────────────────────────💦☁
class STAFFMONS_ROLES:

    fluorescence = 1407468503748968468
    meowhelper = 1407469885419819028
    espeon = 1407480866330116099
    pokémeow = 1407527913619984477
    iriselle = 1407542699464331305
    as_spawn = 1407543490711261426
    as_rare_spawn = 1407543531723161682
